name: Scan image

on:
  push:
  workflow_dispatch:

jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for the GitHub Action.
    steps:
      - uses: actions/checkout@v4
      # Use Central Login to get credentials and set up environment variables for other steps.
      - name: central-login
        uses: stackrox/central-login@v1
        with:
          endpoint: ${{ secrets.CENTRAL_ENDPOINT }}
          skip-tls-verify: true
      # Look at the current user
      - name: whoami
        run: |
          ./roxctl central whoami --insecure-skip-tls-verify
      # Scan an arbitrary image
      - name: scan nginx image
        run: |
          ./roxctl image check --image docker.io/nginx:1.23 -o table --insecure-skip-tls-verify
